from __future__ import annotations

from collections.abc import AsyncIterator, Mapping
from typing import Protocol, runtime_checkable

from fern.events.event import Event
from fern.completeness.event_receipts import EventReceipt


@runtime_checkable
class EventStore(Protocol):
    async def put_event(self, event: Event) -> None: ...
    async def get_event(self, event_id: str) -> Event | None: ...
    async def has_event(self, event_id: str) -> bool: ...
    def iter_all_events(self) -> AsyncIterator[Event]: ...
    def iter_group_events(self, group: str) -> AsyncIterator[Event]: ...
    def iter_since(self, group: str, since_ts: int) -> AsyncIterator[Event]: ...
    async def count_events(self, group: str) -> int: ...
    async def get_tips(self, group: str) -> list[str]: ...
    async def get_known_set(self, group: str) -> frozenset[str]: ...
    async def get_parent_map(self, group: str) -> Mapping[str, frozenset[str]]: ...
    async def get_hosted_groups(self) -> list[str]: ...
    async def delete_event(self, event_id: str) -> None: ...


@runtime_checkable
class EventReceiptStore(Protocol):
    async def put_event_receipt(self, event_id: str, relay_pubkey: str, event_receipt: EventReceipt) -> None: ...
    async def get_event_receipt(self, event_id: str, relay_pubkey: str) -> EventReceipt | None: ...
    def iter_event_receipts_for_event(self, event_id: str) -> AsyncIterator[EventReceipt]: ...
